name: dart_config
version: 0.5.0
author: Chris Buckett <chrisbuckett@gmail.com>
description: A set of libraries designed to provide configuration to Dart applications. Using dependency injection, the same library API can load config information from the filesystem and httprequest, formatted as JSON or YAML.  Customization with additional providers is also possible by implementing two simple interfaces.
homepage: https://github.com/chrisbu/dart_config
dependencies:
  yaml: '>=0.4.2'
dev_dependencies:
  test: '^1.3.4'
environment:
  sdk: '>=1.19.0 <3.0.0'
